const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const startScreen=document.querySelector('#start-screen'),death=document.querySelector('#death'),start=document.querySelector('#start'),restart=document.querySelector('#restart');
const distanceEl=document.querySelector('#distance'),biomeEl=document.querySelector('#biome'),boostEl=document.querySelector('#boost'),eventEl=document.querySelector('#event');
const memory=document.querySelector('#memory'),memoryPhase=document.querySelector('#memory-phase'),memoryNumber=document.querySelector('#memory-number'),doors=document.querySelector('#doors'),leftDoor=document.querySelector('#door-left'),rightDoor=document.querySelector('#door-right');
const W=canvas.width,H=canvas.height;const keys={};let game=null,last=0,raf=0;
const biomes=[['HIGHWAY',0,2800],['DESERT',2800,5500],['JUNGLE',5500,8500],['DEAD CITY',8500,11500],['RED FOREST',11500,14500],['THE HOLLOW',14500,18000],['MONSTER WORLD',18000,Infinity]];
const monsterTypes=['The Stranger','The Long Walker','The Hollow Woman','The Bent Man','The Needle','The Watcher','The Passenger','The Twin','The Runner','The Smiler','The Tall Child','The Road Bride','The Antler','The Crawling One','The Window Face','The Backward Walker','The Pale Driver','The Bellman','The Split Figure','The Thin One','The Mirror Twin','The Sleeper','The Red Giant','The Distant Woman','The Bent Child','The Long Arms','The Empty Suit','The Black Deer','The False Friend','The Stilt Man','The Face in the Fog','The Double','The Crooked One','The Runner Two','The Tower','The Pale Group','The Mouth','The Guest','The Red Walker','The Last Stranger'];
const disguise=new Set([0,2,9,10,11,18,24,26,28,32,37]);const chase=new Set([1,4,8,13,16,22,25,29,33,38]);const loopers=new Set([6,7,15,20,23,31,35]);
function reset(){game={running:false,d:0,x:W/2,boost:0,burst:0,threat:0,threatTimer:5,monsterTimer:4,memoryTimer:0,monsters:[],pickups:[],particles:[],marks:[],biome:0,shake:0,red:0,loop:0};for(let i=0;i<24;i++)game.marks.push(i*50);memory.classList.add('hidden');death.classList.add('hidden');distanceEl.textContent='0m';biomeEl.textContent='HIGHWAY';boostEl.textContent='—';eventEl.textContent='';draw()}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}function rand(a,b){return a+Math.random()*(b-a)}function pick(a){return a[Math.floor(Math.random()*a.length)]}function smooth(a,b,x){let t=clamp((x-a)/(b-a),0,1);return t*t*(3-2*t)}
function event(t){eventEl.textContent=t;clearTimeout(event._t);event._t=setTimeout(()=>eventEl.textContent='',1800)}
function biome(){let i=biomes.findIndex(b=>game.d>=b[1]&&game.d<b[2]);if(i<0)i=6;if(i!==game.biome){game.biome=i;event(biomes[i][0])}game.biome=i;biomeEl.textContent=biomes[i][0]}
function road(){return game.d<2800}
function spawnBoost(){game.pickups.push({x:road()?rand(W*.38,W*.62):rand(35,W-35),y:-30})}
function useBoost(){if(!game.running||game.boost<1)return;game.boost=0;game.burst=2.5;game.threat=0;game.shake=.35;event('BOOST');for(let i=0;i<15;i++)game.particles.push({x:game.x+rand(-15,15),y:H-95,life:.5,vx:rand(-50,50),vy:rand(60,180)})}
function monster(){let max=Math.min(monsterTypes.length,6+Math.floor(game.d/450)),id=Math.floor(Math.random()*max);game.monsters.push({id,name:monsterTypes[id],x:road()?rand(W*.35,W*.65):rand(30,W-30),y:-90,age:0,reveal:!disguise.has(id),kind:chase.has(id)?'chase':loopers.has(id)?'loop':'always',speed:rand(35,85),scale:rand(.8,1.25),phase:rand(0,7),life:7})}
function encounter(){let chance=.25+smooth(0,18000,game.d)*.5;if(Math.random()<chance)monster();if(game.d>500&&Math.random()<.1+game.d/30000)monster()}
function memoryGame(){if(game.memoryTimer||!game.running)return;let digits=game.d<400?2:game.d<2500?3:game.d<6000?4:game.d<9500?5:game.d<13000?6:7;let n=String(Math.floor(rand(10**(digits-1),10**digits)));if(digits===2&&Math.random()<.35)n='22';let fake=n.split('');let k=Math.floor(Math.random()*digits);fake[k]=String((+fake[k]+(Math.random()<.5?1:9))%10);game.memory={answer:n,fake:fake.join('')};game.memoryTimer=2.2;memoryPhase.classList.remove('hidden');doors.classList.add('hidden');memoryNumber.textContent=n;memory.classList.remove('hidden');event('REMEMBER')}
function showDoors(){game.memoryTimer=-1;memoryPhase.classList.add('hidden');doors.classList.remove('hidden');let a=game.memory.answer,b=game.memory.fake;if(Math.random()<.5){leftDoor.textContent=a;rightDoor.textContent=b}else{leftDoor.textContent=b;rightDoor.textContent=a}}
function choose(v){if(!game.memory||game.memoryTimer!==-1)return;if(v===game.memory.answer){game.memory=null;game.memoryTimer=0;memory.classList.add('hidden');event('CORRECT')}else end('WRONG DOOR')}
function end(reason){if(!game.running)return;game.running=false;death.classList.remove('hidden');document.querySelector('#death-title').textContent=reason;document.querySelector('#death-score').textContent=`You reached ${Math.floor(game.d)}m.`}
function update(dt){if(!game.running)return;if(game.memoryTimer>0){game.memoryTimer-=dt;if(game.memoryTimer<=0)showDoors();return}if(game.memoryTimer===-1)return;
let danger=smooth(2500,18000,game.d),move=((keys.ArrowRight||keys.d)?1:0)-((keys.ArrowLeft||keys.a)?1:0);game.x+=move*(road()?285:470+danger*80)*dt;if(road()){let c=W/2+Math.sin(game.d*.004)*28,h=125;game.x=clamp(game.x,c-h,c+h)}else game.x=clamp(game.x,18,W-18);
let speed=105+danger*55+(game.burst>0?175:0);game.d+=speed*dt;game.burst=Math.max(0,game.burst-dt);game.shake=Math.max(0,game.shake-dt*1.8);game.red=Math.max(0,game.red-dt*1.5);biome();
for(let i=0;i<game.marks.length;i++){game.marks[i]+=speed*dt;if(game.marks[i]>H+30)game.marks[i]=-30}
for(const p of game.pickups)p.y+=speed*dt;game.pickups=game.pickups.filter(p=>{if(Math.hypot(p.x-game.x,p.y-(H-100))<32){game.boost=1;event('BOOST READY');return false}return p.y<H+40});
if(Math.random()<dt*(.08+danger*.13))spawnBoost();game.monsterTimer-=dt;if(game.monsterTimer<=0){encounter();game.monsterTimer=Math.max(.8,rand(3.5,6)-danger*2)}
if(game.d>900&&Math.random()<dt*(.012+danger*.025))memoryGame();
for(const m of game.monsters){m.age+=dt;m.y+=(speed*.72+m.speed)*dt;if(m.kind==='chase'||(m.reveal&&disguise.has(m.id))){m.x+=Math.sign(game.x-m.x)*(50+danger*130)*dt}if(disguise.has(m.id)&&!m.reveal&&m.y>H*.45){m.reveal=true;game.red=.7;game.shake=.5;event(m.name.toUpperCase())}if(m.kind==='loop'&&m.y>H*.45&&!m.reveal){m.reveal=true;event('THAT PERSON AGAIN')}}
let near=game.monsters.find(m=>m.reveal&&Math.abs(m.y-(H-100))<115&&Math.abs(m.x-game.x)<48&&(m.kind==='chase'||disguise.has(m.id)));if(near){if(game.burst<=0){game.threat+=dt;game.red=.45;game.shake=.25;if(game.threat>.9&&!game.boost)end('SHE CAUGHT UP');if(game.boost)event('BOOST TO ESCAPE')}}
game.monsters=game.monsters.filter(m=>m.y<H+130&&m.life>0);game.threatTimer-=dt;if(game.threatTimer<=0){game.threatTimer=rand(7,14)-danger*4;if(Math.random()<.45+danger*.3){game.threat=.35;game.red=.55;game.shake=.4;event('SHE IS CLOSER')}}
if(Math.random()<dt*10)game.particles.push({x:game.x+rand(-8,8),y:H-75,life:.25,vx:rand(-20,20),vy:rand(20,60)});for(const p of game.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt}game.particles=game.particles.filter(p=>p.life>0);
distanceEl.textContent=Math.floor(game.d)+'m';boostEl.textContent=game.boost?'READY':'—'}
function pixelRect(x,y,w,h){ctx.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h))}
function drawBike(){let x=game.x,y=H-100;ctx.save();ctx.translate(x,y);ctx.fillStyle='#080808';ctx.fillRect(-7,5,14,43);ctx.fillRect(-25,28,50,9);ctx.fillStyle='#ddd';ctx.fillRect(-12,-8,24,19);ctx.fillStyle='#222';ctx.fillRect(-8,-20,16,14);ctx.fillStyle='#bbb';ctx.fillRect(-4,-24,8,5);ctx.fillStyle='#555';ctx.fillRect(-18,42,10,7);ctx.fillRect(8,42,10,7);ctx.restore()}
function drawWorld(){let r=smooth(0,18000,game.d);ctx.fillStyle=`rgb(${12+Math.floor(r*75)},${18-Math.floor(r*10)},${27-Math.floor(r*15)})`;ctx.fillRect(0,0,W,H);let b=game.biome;
if(b===0){ctx.fillStyle='#18171b';ctx.beginPath();ctx.moveTo(W*.27,0);ctx.lineTo(W*.73,0);ctx.lineTo(W*.86,H);ctx.lineTo(W*.14,H);ctx.fill();ctx.fillStyle='#ddd';for(const y of game.marks)ctx.fillRect(W/2-3,y,6,25)}
if(b===1){ctx.fillStyle='#7c654b';ctx.fillRect(0,H*.62,W,H*.38);ctx.fillStyle='#a08a62';for(let i=0;i<14;i++){let x=(i*83+game.d*.04)%W;ctx.fillRect(x,H*.58,3,50)}}
if(b===2){ctx.fillStyle='#10251b';ctx.fillRect(0,H*.55,W,H*.45);for(let i=0;i<12;i++){let x=(i*71+game.d*.08)%W;ctx.fillStyle='#23452c';ctx.fillRect(x,H*.25,13,300);ctx.fillRect(x-25,H*.25,60,10)}}
if(b===3){ctx.fillStyle='#242329';ctx.fillRect(0,H*.58,W,H*.42);for(let i=0;i<10;i++){let x=(i*91+game.d*.06)%W;ctx.fillStyle='#454149';ctx.fillRect(x,H*.3,48,270);ctx.fillStyle='#d0a83c';ctx.fillRect(x+10,H*.38,7,12)}}
if(b===4){ctx.fillStyle='#24171a';ctx.fillRect(0,H*.55,W,H*.45);for(let i=0;i<18;i++){let x=(i*59+game.d*.1)%W;ctx.fillStyle='#3d2425';ctx.fillRect(x,H*.15,8,390);ctx.fillRect(x-20,H*.25,48,9)}}
if(b>=5){ctx.fillStyle='#090608';ctx.fillRect(0,H*.55,W,H*.45);for(let i=0;i<16;i++){let x=(i*97+game.d*.12)%W;ctx.fillStyle='#27141c';ctx.fillRect(x,H*.1,5,450);ctx.fillRect(x-30,H*.18,70,7)}}}
function drawMonster(m){let x=m.x,y=m.y,s=m.scale*(m.reveal?1:0.7);ctx.save();ctx.translate(x,y);ctx.globalAlpha=.9;if(!m.reveal){ctx.fillStyle='#b9b2a7';pixelRect(-8,-35,16,28);pixelRect(-14,-7,28,36);pixelRect(-20,4,7,35);pixelRect(13,4,7,35);ctx.fillStyle='#111';pixelRect(-5,-25,3,3);pixelRect(3,-25,3,3)}else{ctx.fillStyle='#171116';ctx.beginPath();ctx.ellipse(0,0,18*s,35*s,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#0a0709';ctx.lineWidth=7*s;ctx.beginPath();ctx.moveTo(-10,25);ctx.lineTo(-45,75);ctx.moveTo(10,25);ctx.lineTo(45,80);ctx.moveTo(-12,-8);ctx.lineTo(-55,-48);ctx.moveTo(12,-8);ctx.lineTo(55,-55);ctx.stroke();ctx.fillStyle='#eee';ctx.fillRect(-9,-12,6,9);ctx.fillRect(4,-12,6,9);if(m.id%3!==0){ctx.fillStyle='#050505';ctx.beginPath();ctx.ellipse(0,15,12,19,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#bda9ad';ctx.fillRect(-6,14,12,3)}}ctx.restore()}
function draw(){ctx.save();if(game?.shake)ctx.translate(rand(-1,1)*game.shake*12,rand(-1,1)*game.shake*12);drawWorld();if(game){for(const p of game.pickups){ctx.fillStyle='#eee';ctx.fillRect(p.x-9,p.y-9,18,18);ctx.fillStyle='#111';ctx.fillRect(p.x-3,p.y-3,6,6)}for(const m of game.monsters)drawMonster(m);drawBike();for(const p of game.particles){ctx.globalAlpha=Math.max(0,p.life/.5);ctx.fillStyle='#aaa';ctx.fillRect(p.x,p.y,3,3)}if(game.red){ctx.globalAlpha=game.red*.22;ctx.fillStyle='#f00';ctx.fillRect(0,0,W,H)}ctx.globalAlpha=1}ctx.restore()}
function loop(t){let dt=Math.min(.035,(t-last)/1000||0);last=t;update(dt);draw();raf=requestAnimationFrame(loop)}
start.onclick=()=>{reset();game.running=true;startScreen.classList.add('hidden');last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop)};restart.onclick=()=>{reset();game.running=true;death.classList.add('hidden');last=performance.now()};leftDoor.onclick=()=>choose(leftDoor.textContent);rightDoor.onclick=()=>choose(rightDoor.textContent);addEventListener('keydown',e=>{keys[e.key]=true;if([' ','Shift'].includes(e.key)){e.preventDefault();useBoost()}});addEventListener('keyup',e=>keys[e.key]=false);reset();